<?php

// autoload_psr4.php @generated by Composer

$smtpDir = dirname(dirname(__FILE__));
$baseDir = dirname($smtpDir);

return array(
    'phpseclib\\' => array($smtpDir . '/phpseclib/phpseclib/phpseclib'),
    'Psr\\Log\\' => array($smtpDir . '/psr/log/Psr/Log'),
    'Psr\\Http\\Message\\' => array($smtpDir . '/psr/http-message/src'),
    'Psr\\Cache\\' => array($smtpDir . '/psr/cache/src'),
    'Monolog\\' => array($smtpDir . '/monolog/monolog/src/Monolog'),
    'GuzzleHttp\\Psr7\\' => array($smtpDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($smtpDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($smtpDir . '/guzzlehttp/guzzle/src'),
    'Google\\Auth\\' => array($smtpDir . '/google/auth/src'),
    'Firebase\\JWT\\' => array($smtpDir . '/firebase/php-jwt/src'),
    'Composer\\Installers\\' => array($smtpDir . '/composer/installers/src/Composer/Installers'),
);
