<?php

// autoload_classmap.php @generated by Composer

$smtpDir = dirname(dirname(__FILE__));
$baseDir = dirname($smtpDir);

return array(
    'Google_Service_Exception' => $smtpDir . '/google/apiclient/src/Google/Service/Exception.php',
    'Google_Service_Resource' => $smtpDir . '/google/apiclient/src/Google/Service/Resource.php',
);
