<?php

// autoload_namespaces.php @generated by Composer

$smtpDir = dirname(dirname(__FILE__));
$baseDir = dirname($smtpDir);

return array(
    'Google_Service_' => array($smtpDir . '/google/apiclient-services/src'),
    'Google_' => array($smtpDir . '/google/apiclient/src'),
);
